import { Comment } from './Comment'

export interface ProductType {
  productRating: {
    voteCount: {
      five: number
      four: number
      three: number
      two: number
      one: number
    }
    rating: number
  }
  _id: string
  images: string[]
  title: string
  price: number
  parentCategory:
    | 'fruits'
    | 'vegetables'
    | 'coffee&tea'
    | 'diary&eggs'
    | 'meat'
    | 'honey'
    | 'flowers'
    | 'driedFruits'
  category:
    | 'Bananas'
    | 'Oranges'
    | 'Apples'
    | 'Mangoes'
    | 'Pinapples'
    | 'Strawberries'
    | 'Potatoes'
    | 'Onions'
    | 'Tomatoes'
    | 'Brinjals'
    | 'Cauliflower'
    | 'Spinach'
    | 'Carrots'
    | 'Tea'
    | 'Coffee'
    | 'Milk'
    | 'Butter'
    | 'Cheese'
    | 'Eggs'
    | 'Goat'
    | 'Sheep'
    | 'Chicken'
    | 'Honey'
    | 'Beewax'
    | 'Pollen'
    | 'Rose'
    | 'Orchids'
    | 'Sunflowers'
    | 'Lillies'
    | 'Tulips'
    | 'Dahlia'
    | 'Pistachios'
    | 'Apricot'
    | 'Dates'
    | 'Cashew'
    | 'Almonds'
  farmerID: string
  farmerName: string
  isVisible: boolean
  hasDiscount: boolean
  discountPercentage: number
}

export interface ProductDetailType {
  productRating: {
    voteCount: {
      five: number
      four: number
      three: number
      two: number
      one: number
    }
    rating: number
  }
  _id: string
  images: File
  title: string
  price: number
  parentCategory:
    | 'fruits'
    | 'vegetables'
    | 'coffee&tea'
    | 'diary&eggs'
    | 'meat'
    | 'honey'
    | 'flowers'
    | 'driedFruits'
  category:
    | 'Bananas'
    | 'Oranges'
    | 'Apples'
    | 'Mangoes'
    | 'Pinapples'
    | 'Strawberries'
    | 'Potatoes'
    | 'Onions'
    | 'Tomatoes'
    | 'Brinjals'
    | 'Cauliflower'
    | 'Spinach'
    | 'Carrots'
    | 'Tea'
    | 'Coffee'
    | 'Milk'
    | 'Butter'
    | 'Cheese'
    | 'Eggs'
    | 'Goat'
    | 'Sheep'
    | 'Chicken'
    | 'Honey'
    | 'Beewax'
    | 'Pollen'
    | 'Rose'
    | 'Orchids'
    | 'Sunflowers'
    | 'Lillies'
    | 'Tulips'
    | 'Dahlia'
    | 'Pistachios'
    | 'Apricot'
    | 'Dates'
    | 'Cashew'
    | 'Almonds'
  farmerID: string
  farmerName: string
  isVisible: boolean
  delivery: boolean
  organic: boolean
  transaction: boolean
  cashOnDelivery: boolean
  returnableChoice: boolean
  hasDiscount: boolean
  discountPercentage: number
  onSiteShopping: boolean
  comments: Comment[]
}
export interface ProductDetailTypeForDisplay {
  productRating: {
    voteCount: {
      five: number
      four: number
      three: number
      two: number
      one: number
    }
    rating: number
  }
  _id: string
  images: string[]
  title: string
  price: number
  parentCategory:
    | 'fruits'
    | 'vegetables'
    | 'coffee&tea'
    | 'diary&eggs'
    | 'meat'
    | 'honey'
    | 'flowers'
    | 'driedFruits'
  category:
    | 'Bananas'
    | 'Oranges'
    | 'Apples'
    | 'Mangoes'
    | 'Pinapples'
    | 'Strawberries'
    | 'Potatoes'
    | 'Onions'
    | 'Tomatoes'
    | 'Brinjals'
    | 'Cauliflower'
    | 'Spinach'
    | 'Carrots'
    | 'Tea'
    | 'Coffee'
    | 'Milk'
    | 'Butter'
    | 'Cheese'
    | 'Eggs'
    | 'Goat'
    | 'Sheep'
    | 'Chicken'
    | 'Honey'
    | 'Beewax'
    | 'Pollen'
    | 'Rose'
    | 'Orchids'
    | 'Sunflowers'
    | 'Lillies'
    | 'Tulips'
    | 'Dahlia'
    | 'Pistachios'
    | 'Apricot'
    | 'Dates'
    | 'Cashew'
    | 'Almonds'
  farmerID: string
  farmerName: string
  isVisible: boolean
  delivery: boolean
  organic: boolean
  transaction: boolean
  cashOnDelivery: boolean
  returnableChoice: boolean
  hasDiscount: boolean
  discountPercentage: number
  onSiteShopping: boolean
  comments: Comment[]
}

export interface ProductDetailForOrder {
  _id: string
  images: string[]
  title: string
  price: number
  hasDiscount: boolean
  discountPercentage: number
  quantity: number
  category:
    | 'Bananas'
    | 'Oranges'
    | 'Apples'
    | 'Mangoes'
    | 'Pinapples'
    | 'Strawberries'
    | 'Potatoes'
    | 'Onions'
    | 'Tomatoes'
    | 'Brinjals'
    | 'Cauliflower'
    | 'Spinach'
    | 'Carrots'
    | 'Tea'
    | 'Coffee'
    | 'Milk'
    | 'Butter'
    | 'Cheese'
    | 'Eggs'
    | 'Goat'
    | 'Sheep'
    | 'Chicken'
    | 'Honey'
    | 'Beewax'
    | 'Pollen'
    | 'Rose'
    | 'Orchids'
    | 'Sunflowers'
    | 'Lillies'
    | 'Tulips'
    | 'Dahlia'
    | 'Pistachios'
    | 'Apricot'
    | 'Dates'
    | 'Cashew'
    | 'Almonds'
  parentCategory:
    | 'fruits'
    | 'vegetables'
    | 'coffee&tea'
    | 'diary&eggs'
    | 'meat'
    | 'honey'
    | 'flowers'
    | 'driedFruits'
  farmerID: string
  farmerName: string
}
